### ISSUE TITLE
Undefined index: #markup in Drupal\widget\Plugin\Block\WidgetBlock

### ISSUE THREAD

**Issue by brunobless** [md-systems/widget#4]
Notice: Undefined index: #markup in Drupal\widget\Plugin\Block\WidgetBlock->blockForm() (line 158 of profiles/np8/modules/contrib/widget/src/Plugin/Block/WidgetBlock.php).
Drupal\widget\Plugin\Block\WidgetBlock->blockForm(Array, Object)
Drupal\Core\Block\BlockBase->buildConfigurationForm(Array, Object)
Drupal\page_manager\Form\DisplayVariantConfigureBlockFormBase->buildForm(Array, Object, Object, 'dc30c400-124e-4b19-ac00-c6e7101b713e', '699c0bb1-483d-4bcb-955f-95a317c79e32')
call_user_func_array(Array, Array)
Drupal\Core\Form\FormBuilder->retrieveForm('page_manager_display_variant_edit_block_form', Object)
Drupal\Core\Form\FormBuilder->buildForm(Object, Object)
Drupal\Core\Controller\FormController->getContentResult(Object, Object)
call_user_func_array(Array, Array)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber{closure}()
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array)
Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber{closure}()
call_user_func_array(Object, Array)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1)
Stack\StackedHttpKernel->handle(Object, 1, 1)
Drupal\Core\DrupalKernel->handle(Object)

**Comment by arildm** [comment]
Thanks, fixed in 033e53e
